### ISSUE TITLE
可否为 data-value-type 增加一个配置选项

### ISSUE THREAD

**Issue by lanseyujie** [laravel-admin-extensions/china-distpicker#5]
因后端查询时需要得知具体的省市区名称，如果储存地区编号则需要单独维护一张表去获取地区名称，插件是否可以增加一个 `data-value-type` 配置选项来改变前台传入的省市区数据类型。

**Comment by z-song** [comment]
@lanseyujie 已经实现
```php
$form->distpicker(['province_id', 'city_id', 'district_id'])->attribute('data-value-type', 'code');
```

数据文件也整理了一份 https://github.com/laravel-admin-extensions/china-distpicker/blob/master/china_area.sql
