### ISSUE TITLE
sql数据和js数据不一致

### ISSUE THREAD

**Issue by jesse7866** [laravel-admin-extensions/china-distpicker#7]
比如：北京的延庆区
在sql里父级是北京市，id为1；
在js里父级是北京城区，没有id。

**Comment by z-song** [comment]
国家行政区划每年都会调整，这个扩展的依赖包https://github.com/fengyuanchen/distpicker 没有更新到最新的数据，试试下面的数据

https://github.com/krissss/gaode-area-mysql/blob/master/dist/area-data.sql

**Comment by jesse7866** [comment]
谢谢，这个数据要全一些，但是没有父级id

**Comment by z-song** [comment]
@jesse7866 整理了下数据字典文件 https://github.com/laravel-admin-extensions/china-distpicker/blob/master/china_area.sql

**Comment by jesse7866** [comment]
谢谢👍
